apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-instance-decorator.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-instance-decorator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-instance-decorator.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "node-instance-decorator.fullname" . }}
  namespace: {{ .Release.Namespace }}