apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-instance-decorator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-instance-decorator.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{  required "IAM Role ARN must be supplied as value 'serviceAccount.iamRoleArn'." .Values.serviceAccount.iamRoleArn }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}